### ISSUE TITLE
Mega.nz link is down

### ISSUE THREAD

**Issue by WildSpy-tech** [cryptoAlgorithm/nt5src#1] opened 2021-01-28 01:22 UTC
Mega.nz link is down

**Comment by modineandrew** [comment] 2021-01-28 06:34
It's been down for a while now. There might be a new link somewhere, however.

**Comment by 1alessandro1** [comment] 2021-02-04 23:06
[Microsoft leaked source code archive_2020-10-04.torrent.zip](https://github.com/cryptoAlgorithm/nt5src/files/5929043/Microsoft.leaked.source.code.archive_2020-10-04.torrent.zip)

**Comment by cryptoAlgorithm** [comment] 2021-05-18 04:32
Duplicate of #2

**Closed by cryptoAlgorithm** 2021-05-18 04:32 UTC
